# Generated by cucumber-sinatra. (Sat May 28 22:45:12 +0300 2011)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'test/app.rb')

require 'capybara'
require 'capybara/cucumber'

# TODO organize profiles and test frameworks
#require 'rspec'
begin
  require 'minitest/unit'
  World(MiniTest::Assertions)
rescue LoadError
  require 'test/unit'
  World(Test::Unit::Assertions)
end

Capybara.app = TestApp

class TestAppWorld
  include Capybara
  #include RSpec::Expectations
  #include RSpec::Matchers
end

World do
  TestAppWorld.new
end
