# Generated by cucumber-sinatra. (Sat May 28 22:45:12 +0300 2011)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'test/app.rb')

require 'capybara'
require 'capybara/cucumber'

Capybara.app = TestApp
Capybara.save_and_open_page_path = File.expand_path(File.join(File.dirname(__FILE__),'../../tmp'))

class TestAppWorld
  include Capybara
  if defined?(RSpec)
    include RSpec::Expectations
    include RSpec::Matchers
  else
    begin
      include MiniTest::Assertions
    rescue NameError
      include Test::Unit::Assertions
    end
  end
end

World do
  TestAppWorld.new
end
